name: CodeCov

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.12.1"
          activate-environment: true

      - name: Install Chromium
        run: >
          uv run --locked --group app
          python -m playwright install --with-deps chromium

      - name: Generate coverage report
        run: >
          uv run --locked --group app python -m pytest
          --cov=src/nhp
          --cov-branch
          --cov-report xml:coverage.xml
          tests/unit

      - name: Run end-to-end smoke tests
        run: >
          uv run --locked --group app
          python -m pytest tests/e2e

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
