name: Linting and Type checking

on: pull_request

jobs:
  ruff-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.12.1"

      - name: Lint
        run: uv run --locked ruff check .

  ruff-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.12.1"

      - name: Check formatting
        run: uv run --locked ruff format --check --diff .

  ty-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.12.1"

      - name: Type check
        run: uv run --locked --group app ty check .
